environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - java -version
  - mvn --version

build_script:
  - mvn -B -V -Prun-its clean verify

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2